<?php
/*
 * DO NOT EDIT THIS FILE
*/
define ('DB_USER', "xgstbfqourfyfc");
define ('DB_PASSWORD', "(50d34ccc7baa6da65898c574bb3689dd8009a5a51c166a13348c02613df5268a)");
define ('DB_DATABASE', "d9oiidgf8b85911");
define ('DB_HOST', "ec2-3-216-129-140.compute-1.amazonaws.com");
